name: Dummy Deployment

on:
  push:
    branches:
      - master

jobs:
  dummy-deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://testurlshortner.up.railway.app

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simulate deployment
        run: echo "Pretending to deploy to production..."

      - name: Display deployed URL
        run: echo "App is live at https://testurlshortner.up.railway.app"
